# Generated by Django 3.0.8 on 2020-08-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_ladderdata_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladderdata',
            name='preferences',
        ),
    ]
