# Generated by Django 3.0.8 on 2020-09-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_ladderdata_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladderdata',
            name='ladder_length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ladderdata',
            name='ladder_point',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ladderdata',
            name='user_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
