# Generated by Django 3.0.8 on 2020-09-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200904_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='GelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='gel_images')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='user_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
